#!/usr/bin/env sh
set -eu

REAL_MOON="${REAL_MOON:-$HOME/.moon/bin/moon}"

if [ "$#" -ge 2 ] && [ "$1" = "fmt" ] && [ "$2" = "--deny-warn" ]; then
  shift 2
  exec "$REAL_MOON" fmt --check "$@"
fi

if [ "$#" -ge 2 ] && [ "$1" = "info" ] && [ "$2" = "--deny-warn" ]; then
  shift 2
  exec "$REAL_MOON" info "$@"
fi

exec "$REAL_MOON" "$@"
